/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2021-05-28 16:18:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>\r\n");
      out.write("About Us\r\n");
      out.write("</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#eaecee\">\r\n");
      out.write("<h1 align=center><font color=\"black\" size=22>About Us</font></h1><br>\r\n");
      out.write("<p><font color=\"#000080\" size=5>The launch of Online Spices Store from the house of Spices  services is exclusively designed to meet the commercial and personal  needs of our customers in both urban and rural destinations. We are emerging as a top destination for a same-day transportation and are continuously serving our customers 24/7/365. We constantly expand our resources to cater to our customer expectation addressing their unique market needs. Our experienced and committed management team with over a decade of industry experience strives to deliver nothing but the best to our customers.\r\n");
      out.write("\r\n");
      out.write("Online Spices Store was founded in the year 1999 and initially serviced Bangalore. Our extensive delivery network is spread across bangalore.</font></p><br>\r\n");
      out.write("<p><font color=\"#FF00FF\" size=5>Our Mission</font><br>\r\n");
      out.write("<font color=\"#000080\" size=5>We endeavor to become the front runner in the marketing business matching the clientsâ needs. We connect the length and breadth of bangalore. We believe in sustainable solutions, friendly business approach and efficient performance establishing us as a leader in the marketing industry.</font></p><br>\r\n");
      out.write("<p><font color=\"#FF00FF\" size=5>Our Vision</font><br>\r\n");
      out.write("<font color=\"#000080\" size=5>We are a reliable marketing partner endeavoring to exceed customer expectations and building a long-term bonding with client by offering bespoke solutions to meet their business and personal goals. We believe in mutual growth and take necessary steps to understand the customer needs before offering a solution. Motivated to offer reliable marketing solutions.</font></p>\r\n");
      out.write("<div align=\"center\" style=\"background-color:lightblue\">\r\n");
      out.write("<table cellspacing=15 >\r\n");
      out.write("<tr>\r\n");
      out.write("<td rowspan=4><img src=\"image/location.JPG\" height=130 width=60></td><td>Online Spices Store</td><td></td><td></td><td></td><td></td>\r\n");
      out.write("<td>Email :info@spices.com</td></tr><tr><td>No 91, 11th cross</td><td></td><td></td><td></td><td></td>\r\n");
      out.write("<td>Web:www.onlinespices.com</td></tr><tr><td>Shanthinagar</td><td></td><td></td><td></td><td></td>\r\n");
      out.write("<td>Contact:080-80808080</td></tr><tr><td>Bangalore-560027</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write("<tr><td colspan=2>© All Rights Reserved For Sjrc-2019</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
