/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2021-05-28 16:17:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Connection.jsp", Long.valueOf(1622217366315L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

Connection con=null;
try
{
	Class.forName("com.mysql.jdbc.Driver");
	con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","mysql");
	System.out.println("CONNECTION SUCCESSFULLY");
}catch (Exception e) 
{
	System.out.println("Error in connection "+e);
}
	

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");

try{
	if((session.getAttribute("username")).equals(null)){
		request.getRequestDispatcher("LoginError.jsp").forward(request, response);
		}
}catch(NullPointerException npe){
	npe.printStackTrace();
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (true) {
        _jspx_page_context.forward("LoginError.jsp");
        return;
      }
      out.write('\r');
      out.write('\n');
      out.write('	');

	
}

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en-US\" >\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/cart.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("<form name=\"f1\" action=\"cartaction.jsp\">\r\n");
      out.write("\r\n");

	
 int user=Integer.parseInt(session.getAttribute("username").toString());  

      out.write("\r\n");
      out.write("\r\n");
      out.write("<p class=\"p1\" align=\"center\">Order Summary</p>\r\n");

			if(request.getParameter("msg") != null)
			{
			String msg=request.getParameter("msg");
			
			
				out.println("<p align='center' style='color:black'> "+request.getParameter("msg")+"</p>");
			
			}
			
      out.write('\r');
      out.write('\n');

			String sql2="select orderid,odate from orders where cid=? and status='oncart'";
			PreparedStatement ps2=con.prepareStatement(sql2);
			ps2.setInt(1,user);
			ResultSet rs1=ps2.executeQuery();
			if(rs1.next())
			{
				int orderid=rs1.getInt(1);
				String sql="select a.pid,a.pname,a.pdesc,a.pprice,b.refid from product a,cart b where b.pid=a.pid and b.orderid=?";
				PreparedStatement ps=con.prepareStatement(sql);
				ps.setInt(1,orderid);
				ResultSet rs=ps.executeQuery();
				
				if(rs.next()){
					rs.previous();
				
      out.write("\r\n");
      out.write("\t\t\t\t<table  align=\"center\" class=\"tbl\" border=2>\r\n");
      out.write("\t\t\t\t<tr ><td colspan=10 align=\"center\" class=\"ois\">Order Id  <input type=\"text\" Name=\"orderid\" readonly=\"readonly\" value=\"");
      out.print(orderid);
      out.write("\"></td></tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t  <th>Product ID </th>\r\n");
      out.write("\t\t\t\t  <th>Name</th>\r\n");
      out.write("\t\t\t\t  <th>Description</th>\r\n");
      out.write("\t\t\t\t  <th>Unit Price</th>\r\n");
      out.write("\t\t\t\t  <th>Quantity</th>\r\n");
      out.write("\t\t\t\t  <th>Total Price</th>\r\n");
      out.write("\t\t\t\t  <th>Remove</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t");

				
				while(rs.next()){

      out.write("\r\n");
      out.write("<td>");
      out.print(rs.getInt(1) );
      out.write("<input type=\"hidden\" name=\"pid\" value=\"");
      out.print(rs.getInt(1) );
      out.write("\"></td>\r\n");
      out.write("<td>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(rs.getString(3) );
      out.write("</td>\r\n");
      out.write("<td >");
      out.print(rs.getFloat(4) );
      out.write("<input type=\"hidden\" name=\"mrp\" value=\"");
      out.print(rs.getFloat(4) );
      out.write("\"></td>\r\n");
      out.write("\r\n");
      out.write("<td><input type=\"text\" name=\"qty\" maxlength=\"2\" onchange=\"myFunction()\" > </td>\r\n");
      out.write("\r\n");
      out.write("<td><input type=\"text\" name=\"subtotal\" readonly=\"readonly\" ></td>\r\n");
      out.write("<td><a href=\"deleteproduct.jsp?refid=");
      out.print(rs.getInt(5));
      out.write("\">Remove</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
}}
			else
			{
				response.sendRedirect("userviewproduct.jsp?&frm=Cartform&msg=Cart is Empty");
			}
			}
			
      out.write("\r\n");
      out.write("<tr class=\"hh1\">\r\n");
      out.write("   <td colspan=4></td><td>NET AMOUNT</td>\r\n");
      out.write("   <td colspan=2><input type=\"text\" name=\"netamt\" readonly=\"readonly\" /></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<table align=\"center\"  cellspacing=15 >\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <td><input type=\"submit\" value=\"Place An Order\"></td>\r\n");
      out.write("       \t<td ><input type=\"submit\" value=\"Back To Shop\" onclick=\"call()\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function myFunction(){\r\n");
      out.write("\tvar the_sum = 0,st=0;\r\n");
      out.write("var the_fields = document.getElementsByName(\"qty\");\r\n");
      out.write("var the_fields1 = document.getElementsByName(\"mrp\");\r\n");
      out.write("\r\n");
      out.write("if(the_fields.length==1)\r\n");
      out.write("\t{\r\n");
      out.write("\tst=parseInt(document.f1.qty.value)*parseInt(document.f1.mrp.value);\r\n");
      out.write("\tdocument.f1.subtotal.value=st;\r\n");
      out.write("\tdocument.f1.netamt.value=st;\r\n");
      out.write("\t}\r\n");
      out.write("else\r\n");
      out.write("\t{\r\n");
      out.write("\tfor (var i=0; i<the_fields.length; i++){\r\n");
      out.write("\t\tif (the_fields[i].value != \"\"\r\n");
      out.write("\t\t&& !isNaN(the_fields[i].value))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tst= Number(the_fields[i].value)*Number(the_fields1[i].value);\r\n");
      out.write("\t\t\tdocument.f1.subtotal[i].value=st;\r\n");
      out.write("\t\t\tthe_sum += Number(the_fields[i].value)*Number(the_fields1[i].value);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.f1.netamt.value=the_sum;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function call()\r\n");
      out.write("{\r\n");
      out.write("document.f1.action=\"userviewproduct.jsp\";\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
