/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2021-05-28 16:16:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class prodadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Connection.jsp", Long.valueOf(1622217366315L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

Connection con=null;
try
{
	Class.forName("com.mysql.jdbc.Driver");
	con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","mysql");
	System.out.println("CONNECTION SUCCESSFULLY");
}catch (Exception e) 
{
	System.out.println("Error in connection "+e);
}
	

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Add New Product</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/managepro.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/ValidateForm.js\"></script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"prodaddcode.jsp\" method=\"get\">\r\n");
      out.write("\t<p align=\"center\" class=\"p1\">Add New Product</p>\r\n");
      out.write("\t");

			if(request.getParameter("msg") != null)
			{
			String msg=request.getParameter("msg");
				out.println("<p align='center' style='color:white'> "+request.getParameter("msg")+"</p>");
			}
			
      out.write("\r\n");
      out.write("\t<div class=\"box\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t");

			String sql="select pid from product";
						Statement st=con.createStatement();
						ResultSet rs=st.executeQuery(sql);
						rs.last();
      out.write("\r\n");
      out.write("\t<table class=\"tb\">\r\n");
      out.write("\t\t<tr><td>Product ID</td><td><input type=\"text\" name=\"pid\" value=");
      out.print(rs.getInt(1)+1);
      out.write(" readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t<td>Product Name</td><td><input type=\"text\" name=\"pname\" onkeyup=\"alp(this)\" onkeydown=\"alp(this)\" required=\"required\" autocomplete=\"off\"></td></tr>\r\n");
      out.write("\t\t<tr><td>MRP</td><td><input type=\"number\" name=\"pmrp\" required=\"required\" autocomplete=\"off\"></td><td>Price</td><td><input type=\"number\" name=\"pprice\" required=\"required\" autocomplete=\"off\"></td></tr>\r\n");
      out.write("\t\t<tr><td>Description</td><td><textarea rows=\"5\" cols=\"30\" name=\"pdesc\" onkeyup=\"alpnum(this)\" onkeydown=\"alpnum(this)\"> </textarea>\r\n");
      out.write("\t\t\t<td>Stock</td><td><input type=\"number\" name=\"pstock\" required=\"required\" autocomplete=\"off\"></td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table align=\"center\" cellspacing=\"10\" >\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" value=\"Save\" style=\"width: 200px;\r\n");
      out.write("\t\t\t\t\t\theight: 40px;\r\n");
      out.write("\t\t\t\t\t\tborder: 2px solid rgb(255, 0, 0);\r\n");
      out.write("\t\t\t\t\t\tborder-radius: 6px;\r\n");
      out.write("\t\t\t\t\t\tfont-size: 20px;\"></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"reset\" value=\"Clear\"></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"button\" value=\"Exit\" onclick=\"window.history.back()\"></td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
