/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2021-05-28 16:18:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tandc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>\r\n");
      out.write("Terms and Conditions</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#EAF2F8\">\r\n");
      out.write("<h1 align=\"center\">Terms and Conditions</h1><br>\r\n");
      out.write("<ul type=\"square\" ><font size=5 type=\"Sitka Text\">\r\n");
      out.write("\t<li> The Customer acknowledges that no employee or agent of the Company has any right to make any representation, warranty or promise in relation to the Goods or the sale of the Goods other than as contained in these Terms.</li>\r\n");
      out.write("\t<li>Payments are to be made to the Company without any deduction or discount other than as stated in these Terms or in the relevant invoice or statement.</li>\r\n");
      out.write("\t<li>The Customer must, within 3 days of being notified of their availability, collect or accept delivery of the Goods and pay the invoice price.</li>\r\n");
      out.write("\t<li>If the Customer fails to collect the Goods or accept delivery within 5 days of being notified of their availability, the Company may terminate this contract, keep the deposit and resell the Goods.</li>\r\n");
      out.write("\t<li> The Company reserves the right to deliver the Goods in whole or in instalments, as well as to deliver prior to the date for delivery and, in such event, the Customer must not refuse to take delivery of the Goods.</li>\r\n");
      out.write("\t<li>Legal and beneficial ownership of the Goods will not pass to the Customer until such time as the Goods have been paid in full in cash.</li>\r\n");
      out.write("\t<li>The Goods are entirely at the risk of the Customer from the moment of delivery to the Customerâs point of delivery or on collection, even though title in the Goods has not passed to the Customer at that time.</li>\r\n");
      out.write("\t<li>The Customer must, at its own expense, maintain the Goods and insure them for the benefit of the Company against theft, breakdown, fire, water and other risks as from the moment of delivery to the Customer and until title in the Goods has passed to the Customer.</li>\r\n");
      out.write("\t<li>All Goods supplied are covered by such warranties as are specified by the manufacturer and supplied subject to the product standards detailed by the manufacturer.</li>\r\n");
      out.write("\t<li>On discovery of any defect in the Goods, the Customer must immediately notify the Company in writing of such defect. The Customer must not carry out any remedial work to alleged defective Goods without first obtaining the written consent of the Company to do so.</li>\r\n");
      out.write("\t<li>Any display product or sample inspected by the Customer is solely for the Customerâs convenience and does not constitute a sale by sample.</li>\r\n");
      out.write("\t<li>All Goods supplied are covered by such warranties as are specified by the manufacturer and supplied subject to the product standards detailed by the manufacturer.</li>\r\n");
      out.write("\t</font>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<h1 align=\"right\">Thank you</h1>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
